baseURL = "https://www.thecustomerclass.com"
copyright = "© 2020 Laurence Vincent."
description = "Home of Larry Vincent's MBA Course on Customer Insights and Analysis at USC Marshall School of Business"
enableEmoji = false
googleAnalytics = "UA-86621401-5"
languageCode = "en-us"
theme = "hugo-theme-basic"
title = "The Customer Class"

[markup.goldmark.renderer]
	unsafe = true


[Permalinks]
post = "essays/:slug"
session = "sessions/:slug"
legal = "legal/:slug"

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[params]
author = "Larry Vincent"
authorIcon = "lv-signature-circle.png"
titleEmoji = ":tada:"
twitter = "@lvincent"
mainSections = ["course"]
gtm_id = "GTM-W8RXX28"

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true

[privacy.twitter]
enableDNT = true

[privacy.youtube]
privacyEnhanced = true

[taxonomies]
category = "categories"
tag = "tags"
